Rails:
  Enabled: true
AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'app/channels/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false