default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: <%= Rails.application.credentials.db_user_name %>
  password: <%= Rails.application.credentials.db_user_password %>

development:
  <<: *default
  database: todolistapi_development

test:
  <<: *default
  database: todolistapi_test

production:
  <<: *default
  database: todolistapi_production
